feat: add ability to have function as linkTo parameters
storybooks/storybook-addon-links pull request #23
Opened 2017-02-04 14:46 UTC by mthuret

Link to #22

Allow the ability to filter to redirect to the right story. 

This feature was existing but seems to have disappeared.

2017-02-10 15:18 UTC, mthuret commented
what do you think of this PR @mnmtanish ?

2017-02-10 17:17 UTC, thani-sh requested changes
Cool feature. I'll merge this once the changes are done.

2017-02-10 17:17 UTC, mnmtanish commented on src/preview.js
> +    console.log(resolvedKind)
Please remove this line

2017-02-10 18:55 UTC, mthuret commented
Done :)

2017-03-09 20:57 UTC, mthuret commented
@mnmtanish any news?

2017-04-08 13:56 UTC, merged